# Generated by Django 4.1.6 on 2023-02-12 10:36

import catalog.services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to=catalog.services.real_estate_dir_path, verbose_name='Image')),
                ('cost', models.FloatField(verbose_name='Cost')),
                ('bedroom_count', models.PositiveIntegerField(verbose_name='Bedrooms')),
                ('bathroom_count', models.PositiveIntegerField(verbose_name='Bathrooms')),
                ('total_square', models.FloatField(verbose_name='Total square')),
                ('living_square', models.FloatField(verbose_name='Living_square')),
                ('year_build', models.IntegerField(verbose_name='Year build')),
                ('parking_space_count', models.IntegerField(verbose_name='Parking space count')),
                ('parking_detail', models.CharField(max_length=50, verbose_name='Parking detail')),
                ('deal_type', models.CharField(choices=[('B', 'Buy'), ('R', 'Rent')], max_length=1, verbose_name='Deal type')),
                ('property_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estates', to='catalog.propertytype')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('real_estate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='catalog.realestate')),
            ],
        ),
    ]
